name: C/C++ CI

on:
  push:
    branches: 
      - main
      - test_cpu_set
  pull_request:
    branches: 
      - main 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name  : check user
      run   : whoami
    - name  : check cpu
      run   : cat /sys/devices/system/cpu/online 
    - name  : online cpu 1
      run   : echo 1 > /sys/devices/system/cpu/cpu1/online \
        grep "processor" /proc/cpuinfo
    - name  : test
      run   : make test